export const demoRows = [
  {
    id: 'SHP-001',
    assigned_to: 'Andrea',
    team_id: 'team2',
    validated_manifest_date: '2026-08-02',
    service_month: 'Aug-2026',
    job_file_number: 'JF-2026-001',
    customer: 'Sample Customer A',
    shipper: 'Sample Shipper A',
    mode: 'LCL',
    house_awb_bl: 'HBL-001',
    master_awb_bl: 'MBL-001',
    pre_alert_shipping_documents: '2026-08-01',
    eta: '2026-08-02',
    cw_air_cbm_lcl: '12.30',
    number_of_container: 1,
    description: 'Construction materials',
    dt_computation: '2026-08-02',
    week_no: 32,
    fundcast: 'Yes',
    ata: '2026-08-03',
    port_of_entry: 'Manila',
    location_of_goods: 'Port Area',
    lodgement: '2026-08-04',
    assessed: '2026-08-05',
    paid: '2026-08-05',
    entry_no: 'E-0001',
    selectivity_color: 'GREEN',
    portal_submission: '2026-08-04',
    broker_representative: 'Portal User 1',
    portal_ticket_efile: 'PT-001',
    releasing_date: '2026-08-06',
    liquidation_processor: 'Michael',
    liquidation_tl: 'Anna',
    endorsement_to_biller: '2026-08-06',
    team_leader: 'Ella',
    customs_declarant: 'Andrea',
    received_folder: '2026-08-06',
    billed_date: '',
    efile: '',
    dispatch: '',
    timeline_duty_tax: 0,
    timeline_lodgement: 2,
    timeline_fan: 1,
    timeline_cargo_releasing: 3,
    timeline_liquidation: 0,
    timeline_liquidation_tl: 0,
    timeline_billing: 0,
    timeline_closing: 0,
    current_stage: 'ENDORSED TO BILLER',
    completion: 79,
    next_action: 'RECEIVE FOLDER / BILLING',
    overall_status: 'ACTION DUE',
    days_open: 25,
    last_milestone_date: '2026-08-06',
    delay_action_remarks: 'Sample: Completed shipment within target timeline.'
  },
  {
    id: 'SHP-002',
    assigned_to: 'Ella',
    team_id: 'team1',
    validated_manifest_date: '2026-08-09',
    service_month: 'Aug-2026',
    job_file_number: 'JF-2026-002',
    customer: 'Sample Customer B',
    shipper: 'Sample Shipper B',
    mode: 'AIR',
    house_awb_bl: 'HAWB-002',
    master_awb_bl: 'MAWB-002',
    pre_alert_shipping_documents: '2026-08-08',
    eta: '2026-08-09',
    cw_air_cbm_lcl: '26.50',
    number_of_container: 0,
    description: 'Machine parts',
    dt_computation: '2026-08-09',
    week_no: 33,
    fundcast: 'No',
    ata: '2026-08-10',
    port_of_entry: 'NAIA',
    location_of_goods: 'Warehouse',
    lodgement: '2026-08-10',
    assessed: '',
    paid: '',
    entry_no: 'E-0002',
    selectivity_color: 'YELLOW',
    portal_submission: '2026-08-10',
    broker_representative: 'Portal User 1',
    portal_ticket_efile: 'PT-002',
    releasing_date: '',
    liquidation_processor: '',
    liquidation_tl: '',
    endorsement_to_biller: '',
    team_leader: 'Ella',
    customs_declarant: 'Ella',
    received_folder: '',
    billed_date: '',
    efile: '',
    dispatch: '',
    timeline_duty_tax: 0,
    timeline_lodgement: 1,
    timeline_fan: 0,
    timeline_cargo_releasing: 0,
    timeline_liquidation: 0,
    timeline_liquidation_tl: 0,
    timeline_billing: 0,
    timeline_closing: 0,
    current_stage: 'LODGED',
    completion: 36,
    next_action: 'FOLLOW ASSESSMENT / FAN',
    overall_status: 'ON TRACK',
    days_open: 18,
    last_milestone_date: '2026-08-10',
    delay_action_remarks: 'Sample: Lodged today; awaiting assessment/FAN.'
  },
  {
    id: 'SHP-003',
    assigned_to: 'Aldwin',
    team_id: 'team2',
    validated_manifest_date: '2026-08-05',
    service_month: 'Aug-2026',
    job_file_number: 'JF-2026-003',
    customer: 'Sample Customer C',
    shipper: 'Sample Shipper C',
    mode: 'FCL',
    house_awb_bl: 'HBL-003',
    master_awb_bl: 'MBL-003',
    pre_alert_shipping_documents: '2026-08-04',
    eta: '2026-08-06',
    cw_air_cbm_lcl: '42.00',
    number_of_container: 2,
    description: 'General cargo',
    dt_computation: '2026-08-05',
    week_no: 32,
    fundcast: 'Yes',
    ata: '2026-08-07',
    port_of_entry: 'Manila',
    location_of_goods: 'CY',
    lodgement: '2026-08-06',
    assessed: '2026-08-07',
    paid: '2026-08-07',
    entry_no: 'E-0003',
    selectivity_color: 'RED',
    portal_submission: '2026-08-06',
    broker_representative: 'Portal User 2',
    portal_ticket_efile: 'PT-003',
    releasing_date: '2026-08-08',
    liquidation_processor: 'Anna',
    liquidation_tl: 'Ella',
    endorsement_to_biller: '',
    team_leader: 'Ella',
    customs_declarant: 'Aldwin',
    received_folder: '',
    billed_date: '',
    efile: '',
    dispatch: '',
    timeline_duty_tax: 0,
    timeline_lodgement: 1,
    timeline_fan: 1,
    timeline_cargo_releasing: 1,
    timeline_liquidation: 2,
    timeline_liquidation_tl: 0,
    timeline_billing: 0,
    timeline_closing: 0,
    current_stage: 'LIQUIDATION - PROCESSOR',
    completion: 64,
    next_action: 'TL LIQUIDATION REVIEW',
    overall_status: 'ACTION DUE',
    days_open: 22,
    last_milestone_date: '2026-08-08',
    delay_action_remarks: 'Sample: In liquidation processor stage.'
  },
  {
    id: 'SHP-004',
    assigned_to: 'Joan',
    team_id: 'team1',
    validated_manifest_date: '2026-08-01',
    service_month: 'Aug-2026',
    job_file_number: 'JF-2026-004',
    customer: 'Sample Customer D',
    shipper: 'Sample Shipper D',
    mode: 'AIR',
    house_awb_bl: 'HAWB-004',
    master_awb_bl: 'MAWB-004',
    pre_alert_shipping_documents: '2026-07-31',
    eta: '2026-08-01',
    cw_air_cbm_lcl: '18.00',
    number_of_container: 0,
    description: 'Electronic components',
    dt_computation: '2026-08-01',
    week_no: 31,
    fundcast: 'Yes',
    ata: '2026-08-01',
    port_of_entry: 'NAIA',
    location_of_goods: 'Warehouse',
    lodgement: '2026-08-01',
    assessed: '2026-08-02',
    paid: '2026-08-02',
    entry_no: 'E-0004',
    selectivity_color: 'GREEN',
    portal_submission: '2026-08-01',
    broker_representative: 'Portal User 1',
    portal_ticket_efile: 'PT-004',
    releasing_date: '2026-08-03',
    liquidation_processor: 'Michael',
    liquidation_tl: 'Ella',
    endorsement_to_biller: '2026-08-04',
    team_leader: 'Ella',
    customs_declarant: 'Joan',
    received_folder: '2026-08-04',
    billed_date: '2026-08-05',
    efile: 'Completed',
    dispatch: '2026-08-06',
    timeline_duty_tax: 0,
    timeline_lodgement: 0,
    timeline_fan: 1,
    timeline_cargo_releasing: 2,
    timeline_liquidation: 1,
    timeline_liquidation_tl: 1,
    timeline_billing: 3,
    timeline_closing: 5,
    current_stage: 'CLOSED / DISPATCHED',
    completion: 100,
    next_action: 'COMPLETE',
    overall_status: 'CLOSED',
    days_open: 5,
    last_milestone_date: '2026-08-06',
    delay_action_remarks: 'Sample: Closed shipment for completed KPI count.'
  }
];
